-- Reference DDL for the "prod" (PostgreSQL) profile.
-- ddl-auto is set to "validate" in prod, so schema changes are meant to be
-- applied deliberately (e.g. via a migration tool or this script) rather than
-- auto-generated by Hibernate, matching how a real deployment would be run.

CREATE TABLE IF NOT EXISTS product (
    id          BIGSERIAL PRIMARY KEY,
    sku         VARCHAR(64)  NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL,
    unit_price  NUMERIC(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS dispenser (
    id                BIGSERIAL PRIMARY KEY,
    code              VARCHAR(64)  NOT NULL UNIQUE,
    location          VARCHAR(255) NOT NULL,
    status            VARCHAR(32)  NOT NULL,
    last_serviced_at  TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stock_level (
    id                 BIGSERIAL PRIMARY KEY,
    dispenser_id       BIGINT NOT NULL REFERENCES dispenser(id) ON DELETE CASCADE,
    product_id         BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    quantity           INTEGER NOT NULL DEFAULT 0,
    capacity           INTEGER NOT NULL,
    last_restocked_at  TIMESTAMP,
    CONSTRAINT uq_stock_dispenser_product UNIQUE (dispenser_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_stock_dispenser ON stock_level(dispenser_id);
CREATE INDEX IF NOT EXISTS idx_stock_low_quantity ON stock_level(quantity);
