[dispenser_hosts]
dispenser-prod-01 ansible_host=10.0.1.11 ansible_user=deploy
dispenser-prod-02 ansible_host=10.0.1.12 ansible_user=deploy

[dispenser_hosts:vars]
ansible_python_interpreter=/usr/bin/python3
app_port=8080
